name: Data Scrapping
on:
    push:
        branches:
            - master

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: myenvironment
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: create env file
        run: |
          touch .env
          echo SESSION_ID=${{secrets.SESSION_ID}} >> .env    
          echo SESSION_ID=${{secrets.SESSION_ID}}
      - run: npx yarn
      - run: npx yarn test
