name: CI
on: push
jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          args: install
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          CI: "true"
        with:
          args: npx yarn 
      - name: create env file
        run: |
          touch .env
          echo SESSION_ID=${{ secrets.SESSION_ID }} >> .env    
          echo SESSION_ID=${{ secrets.SESSION_ID }}
      - run: npx yarn
      - run: npx yarn test
